-- Show full room hierarchy
SELECT r.roomID, r.roomNumber, r.baseRate,
       f.floorNumber, w.wingName, b.buildingName
FROM room r
JOIN floor f ON r.floorID = f.floorID
JOIN wing w ON f.wingID = w.wingID
JOIN building b ON w.buildingID = b.buildingID;

-- Find available rooms in a date range
SELECT r.roomID, r.roomNumber, r.roomStatus
FROM room r
WHERE r.roomStatus = 'available'
  AND r.roomID NOT IN (
    SELECT rr.roomId
    FROM room_reservation rr
    WHERE rr.startDateTime < '2026-04-17 12:00'
      AND rr.endDateTime > '2026-04-15 14:00'
);

-- Reserved rooms vs actually assigned rooms
SELECT rr.reservationId,
       rr.roomId AS plannedRoomId,
       r1.roomNumber AS plannedRoomNumber,
       ra.stayId,
       ra.roomId AS actualRoomId,
       r2.roomNumber AS actualRoomNumber
FROM room_reservation rr
LEFT JOIN room r1 ON rr.roomId = r1.roomID
LEFT JOIN room_assignment ra
       ON rr.roomId = ra.roomId
      AND rr.startDateTime = ra.assignedFrom
LEFT JOIN room r2 ON ra.roomId = r2.roomID
ORDER BY rr.reservationId;

-- Events scheduled and rooms used
SELECT e.eventId, e.startDate, e.endDate, r.roomNumber, er.usageSlot
FROM event e
JOIN event_room er ON e.eventId = er.eventId
JOIN room r ON er.roomId = r.roomID
ORDER BY e.eventId, er.usageSlot;

-- Charges associated with a guest
SELECT s.stayId, p.first_name, p.last_name,
       c.chargeId, c.amount, c.chargeDateTime, c.description
FROM charge c
JOIN stay s ON c.stayId = s.stayId
JOIN person p ON s.guestId = p.personId
ORDER BY s.stayId, c.chargeDateTime;

-- Charges associated with an event
SELECT e.eventId, c.chargeId, c.amount, c.chargeDateTime, c.description
FROM charge c
JOIN event e ON c.eventId = e.eventId
ORDER BY e.eventId, c.chargeDateTime;

-- Who is responsible for payment
SELECT c.chargeId, c.amount,
       bp.billingPartyId,
       p.first_name, p.last_name,
       o.organizationId
FROM charge c
JOIN billing_party bp ON c.billingPartyId = bp.billingPartyId
LEFT JOIN person p ON bp.personId = p.personId
LEFT JOIN organization o ON bp.organizationId = o.organizationId
ORDER BY c.chargeId;

-- Revenue by service type
SELECT s.serviceType, ROUND(SUM(c.amount), 2) AS revenue
FROM charge c
JOIN service s ON c.serviceId = s.serviceId
GROUP BY s.serviceType
ORDER BY revenue DESC;

-- Revenue generated by each room
SELECT r.roomNumber, ROUND(SUM(c.amount), 2) AS totalRevenue
FROM charge c
JOIN room r ON c.roomId = r.roomID
GROUP BY r.roomID
ORDER BY totalRevenue DESC;

-- Show bed configuration of each room
SELECT r.roomNumber, bt.size, rb.quantity
FROM room_bed rb
JOIN room r ON rb.roomId = r.roomID
JOIN bed_type bt ON rb.bedTypeId = bt.bedTypeId;

-- Show access logs
SELECT cal.cardId, r.roomNumber, cal.accessTime, cal.direction
FROM card_access_log cal
JOIN room r ON cal.roomId = r.roomID;

-- Track guest access history
SELECT p.first_name, p.last_name, r.roomNumber,
       cal.accessTime, cal.direction
FROM access_card ac
JOIN person p ON ac.guestId = p.personId
JOIN card_access_log cal ON ac.cardId = cal.cardId
JOIN room r ON cal.roomId = r.roomID;
