-- Show full room hierarchy
SELECT r.roomID, r.roomNumber, r.baseRate,
       f.floorNumber, w.wingName, b.buildingName
FROM room r
JOIN floor f ON r.floorID = f.floorID
JOIN wing w ON f.wingID = w.wingID
JOIN building b ON w.buildingID = b.buildingID;
-- Show bed configuration of each room
SELECT r.roomNumber, bt.size, rb.quantity
FROM room_bed rb
JOIN room r ON rb.roomId = r.roomID
JOIN bed_type bt ON rb.bedTypeId = bt.bedTypeId;
-- Show rooms reserved in each reservation
SELECT rr.reservationId, r.roomNumber, rr.startDateTime, rr.endDateTime
FROM room_reservation rr
JOIN room r ON rr.roomId = r.roomID;
-- Reservations for a specific room
SELECT reservationId, startDateTime, endDateTime
FROM room_reservation
WHERE roomId = 101;
-- Show stay history for each guest
SELECT s.guestId, p.first_name, p.last_name, s.checkIn, s.checkOut
FROM stay s
JOIN person p ON s.guestId = p.personId;
-- Show assigned rooms for each stay
SELECT ra.stayId, r.roomNumber, ra.assignedFrom, ra.assignedTo
FROM room_assignment ra
JOIN room r ON ra.roomId = r.roomID;
-- Show rooms used in each event
SELECT er.eventId, r.roomNumber, er.usageSlot
FROM event_room er
JOIN room r ON er.roomId = r.roomID;
-- Total charge per billing party
SELECT billingPartyId, ROUND(SUM(amount), 2) AS total
FROM charge
GROUP BY billingPartyId;
-- Revenue by service type
SELECT s.serviceType, ROUND(SUM(c.amount), 2) AS revenue
FROM charge c
JOIN service s ON c.serviceId = s.serviceId
GROUP BY s.serviceType;
-- Revenue generated by each room
SELECT r.roomNumber, ROUND(SUM(c.amount), 2) AS totalRevenue
FROM charge c
JOIN room r ON c.roomId = r.roomID
GROUP BY r.roomID;
-- Show access logs
SELECT cal.cardId, r.roomNumber, cal.accessTime, cal.direction
FROM card_access_log cal
JOIN room r ON cal.roomId = r.roomID;
-- Track guest access history
SELECT p.first_name, p.last_name, r.roomNumber,
       cal.accessTime, cal.direction
FROM access_card ac
JOIN guest g ON ac.guestId = g.guestId
JOIN person p ON g.guestId = p.personId
JOIN card_access_log cal ON ac.cardId = cal.cardId
JOIN room r ON cal.roomId = r.roomID;
-- Find available rooms in a date range
SELECT r.roomID, r.roomNumber
FROM room r
WHERE r.roomID NOT IN (
    SELECT rr.roomId
    FROM room_reservation rr
    WHERE rr.startDateTime < '2026-04-17 12:00'
      AND rr.endDateTime > '2026-04-15 14:00'
);
-- Guests with multiple stays
SELECT s.guestId, COUNT(*) AS stayCount
FROM stay s
GROUP BY s.guestId
HAVING COUNT(*) > 1;
